#!/usr/bin/env bash
# shellcheck disable=SC2154
# configures a brand new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install ngnix
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/ngnix/ngnix.conf
echo "Holberton School" | sudo tee /usr/share/ngnix/html/index.html
sudo service ngnix start